# Generated by Django 5.2 on 2026-09-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_trees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familytree',
            name='approval_required',
            field=models.BooleanField(default=True),
        ),
    ]
